# shared parameter from experiment
routes: None
routes_subset: None

# output 
save_output: True
output_dir: data/auto
force_destory_actor: True # maybe have better effects!
weather_change: False # whether change the weather
max_stop_num: 300 
debug_print: False # pls remember to set False when collect data 