# shared parameter from experiment
routes: None
routes_subset: None

# agent config
save_output: True
output_dir: data/autopilot
debug_print: False #

waypoint_disturb: 0
waypoint_disturb_seed: 2024
destory_hazard_actors: True

birdview_cache_dir: './'