#shared parameter from experiment
routes: None
routes_subset: None

save_output: True
output_dir: data/interfuser

# model parameters
model: interfuser_baseline
model_path: experts/agents/interfuser/interfuser.pth.tar

# PID controller
turn_KP: 1.25
turn_KI: 0.75
turn_KD: 0.3
turn_n: 40  # buffer size

speed_KP: 5.0
speed_KI: 0.5
speed_KD: 1.0
speed_n: 40  # buffer size

# control limits
max_throttle: 0.75  # upper limit on throttle signal value in dataset
brake_speed: 0.1  # desired speed below which brake is triggered
brake_ratio: 1.1  # ratio of speed to desired speed at which brake is triggered
clip_delta: 0.35  # maximum change in speed input to logitudinal controller

max_speed: 5
collision_buffer: [2.5, 1.2]

momentum: 0
skip_frames: 1
detect_threshold: 0.04