# path config
absolute_path: '/home/yyf/github/self-driving-agents'

# general experiment
track: 'SENSORS' # 'MAP' or 'SENSORS'
resume: False
checkpoint: './checkpoints/_checkpoint.json'
debug_checkpoint: '/checkpoints/_checkpoint_debug.txt'

# carla client/server
host: 'localhost'
port: 2000
traffic_manager_port: 0
traffic_manager_seed: 0
debug: False
record: ''
timeout: 600

# routes
routes: 'leaderboard/data/routes_devtest.xml'
routes_subset: '1'
repetitions: 1

# agents
# simple auto agent
#agent: 'experts/agents/auto/auto_expert.py'
#defaults:
#  - agent_config: auto

# auto pilot agent
#agent: 'experts/agents/autopilot/auto_pilot.py'
#defaults:
#  - agent_config: autopilot

# interfuser agent
agent: 'experts/agents/interfuser/interfuser_agent.py'
defaults:
  - agent_config: interfuser